Repository kbyunghoon/InvestMetic_BE, pull requests merged in 2024-12, with the labels that each got.

#1 🐛 [fix] 전략 통계 백분율 및 일간분석 계산 일부 수정
  src/main/java/com/investmetic/InvestMeticApplication.java
  src/main/java/com/investmetic/domain/file/controller/.gitkeep
  src/main/java/com/investmetic/domain/file/dto/request/.gitkeep
  src/main/java/com/investmetic/domain/file/dto/response/.gitkeep
  src/main/java/com/investmetic/domain/file/model/entity/.gitkeep
  src/main/java/com/investmetic/domain/file/repository/.gitkeep
  src/main/java/com/investmetic/domain/file/service/.gitkeep
  src/main/java/com/investmetic/domain/notice/service/NoticeService.java
  src/main/java/com/investmetic/domain/strategy/model/entity/StrategyStatistics.java
  src/main/java/com/investmetic/domain/strategy/repository/StrategyRepositoryCustomImpl.java
  src/main/java/com/investmetic/domain/strategy/service/StrategyRegisterService.java
  src/main/java/com/investmetic/global/scheduler/DailyAnalysisScheduler.java
  src/main/java/com/investmetic/global/scheduler/StrategyStatisticsScheduler.java
  src/test/java/com/investmetic/global/scheduler/StrategyStatisticsSchedulerTest.java
Labels: bug

#7 :sparkles: [Feat] : 트레이더 프로필 조회
  src/main/java/com/investmetic/domain/user/controller/UserController.java
  src/main/java/com/investmetic/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/investmetic/domain/user/repository/UserRepositoryCustomImpl.java
  src/main/java/com/investmetic/domain/user/service/UserService.java
Labels: documentation, enhancement

#9 :bug: [Bug] : FK 참조 오류 Notice삭제 불가능 기능 개선.
  src/main/java/com/investmetic/domain/notice/service/NoticeService.java
Labels: bug

#10 Feat/delete user
  src/main/java/com/investmetic/domain/user/controller/UserController.java
  src/main/java/com/investmetic/domain/user/repository/UserRepositoryCustomImpl.java
  src/main/java/com/investmetic/domain/user/service/UserService.java
Labels: enhancement

#12 :bug: [Bug] : 관리자가 자기 자신의 등급 변경시 권한 없음으로.
  src/main/java/com/investmetic/domain/user/controller/UserAdminController.java
Labels: bug
