Repository kbyunghoon/InvestMetic_BE, pull requests merged in 2025-02, with the labels that each got.

#44 🐛 [fix] 관리자 회원목록 조회 가입날짜 추가
  src/main/java/com/investmetic/domain/user/dto/response/UserProfileDto.java
  src/main/java/com/investmetic/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/investmetic/domain/user/repository/UserRepositoryCustomImpl.java
  src/test/java/com/investmetic/domain/user/repository/UserRepositoryTest.java
Labels: ✨ Feature, 🐛 fix

#46 🐛 [fix] 월간 분석 누적 손익 계산식 수정
  src/main/java/com/investmetic/global/scheduler/MonthlyAnalysisScheduler.java
Labels: 🐛 fix

#47 🐛 [fix] 권한 검증 로직 수정
  src/main/java/com/investmetic/domain/strategy/service/StrategyAnalysisService.java
Labels: 🐛 fix

#49 [fix] 전략제안서 삭제 추가 및 구독 동시성제어
  src/main/java/com/investmetic/domain/strategy/model/entity/Strategy.java
  src/main/java/com/investmetic/domain/strategy/repository/StrategyRepository.java
  src/main/java/com/investmetic/domain/strategy/service/StrategyService.java
  src/main/java/com/investmetic/domain/subscription/service/SubscriptionService.java
  src/test/java/com/investmetic/domain/subscription/service/ConcurrentSubscriptionTest.java
Labels: 🐛 fix, ♻️ Refactor, ⚡️ Performance
